routes/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.sea_dsr import SEADSR
from models.air_dsr import AIRDSR
from app import db
import csv
from logger import log_args_and_return

main_bp = Blueprint('main_bp', __name__)

@main_bp.route('/',methods=['GET', 'POST'])
@main_bp.route('/login',methods=['GET', 'POST'])
@log_args_and_return
def Index():
    return render_template('login.html')


@main_bp.route('/options')
@log_args_and_return
def options():
    return render_template('index.html')

@log_args_and_return
def add_or_update_record(model_class, record_id=None, **data):
    try:
        if record_id:
            record = model_class.query.get_or_404(record_id)
            for key, value in data.items():
                setattr(record, key, value.upper())
        else:
            record = model_class(**{k: v.upper() for k, v in data.items()})
            db.session.add(record)
        db.session.commit()
        flash(f"Record {'updated' if record_id else 'added'} successfully!")
    except Exception as e:
        flash(f"An error occurred: {str(e)}")


# AIR FUNCTIONS

@main_bp.route('/air',methods=['GET','POST'])
@log_args_and_return
def air():
    try:
        if request.method=="POST":
            data = {field: request.form[field].upper() for field in request.form}
            add_or_update_record(AIRDSR, **data)
            flash("Form Submitted Successfully!")
            return redirect(url_for('main_bp.air'))
        return render_template('air_page.html')
    except Exception as e:
        flash(f"An error occurred: {str(e)}")
        return redirect(url_for('main_bp.air'))
    

@main_bp.route('/dsrairinfo', methods=['GET', 'POST'])
@log_args_and_return
def dsrairinfo():
    airinfo = AIRDSR.query.all()
    air_column_names = AIRDSR.__table__.columns.keys()
    return render_template('Air Homepage.html',air_column_names=air_column_names, airinformation=airinfo)



@main_bp.route('/airupdate',methods=['GET','POST'])
@log_args_and_return
def airupdate():
    if request.method=="POST":
        air_form=AIRDSR.query.get(request.form.get('id'))
        data = {field: request.form[field].upper() for field in request.form if field != 'id'}
        add_or_update_record(AIRDSR, record_id=air_form, **data)
        flash(f"{air_form.ponumber} Has Updated Successfully")
        return redirect(url_for('main_bp.dsrairinfo'))


@main_bp.route('/airdelete/<id>',methods=['GET','POST'])
@log_args_and_return
def airdelete(id):
    try:
        air_form=AIRDSR.query.get_or_404(id)
        db.session.delete(air_form)
        db.session.commit()
        flash(f"{air_form.ponumber} Deleted Successfully")
    except Exception as e:
        flash(f"An error occurred while deleting: {str(e)}")
    return redirect(url_for('main_bp.dsrairinfo'))


@main_bp.route('/airdownload')
@log_args_and_return
def airdownload():
    try:
        # Query data from the database
        data = AIRDSR.query.all()
        # Create a CSV file
        csv_filename = 'airdata.csv'
        with open(csv_filename, 'w', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            # Write header
            csv_writer.writerow([column.name.upper() for column in AIRDSR.__table__.columns])
            # Write data
            for row in data:
                csv_writer.writerow([getattr(row, column.name) for column in AIRDSR.__table__.columns])
        return send_file(csv_filename, as_attachment=True,download_name='airdata.csv')
        # Return the file as a response
    except Exception as e:
        flash(f"An error occurred while downloading: {str(e)}")
        return redirect(url_for('main_bp.dsrairinfo'))

# SEA FUNCTIONS

@main_bp.route('/sea',methods=['GET','POST'])
def sea():
    if request.method=="POST":
        shipmentmode=request.form["shipmentmode"].upper()
        ponumber=request.form["ponumber"].upper()
        suppliername=request.form["suppliername"].upper()
        consignee=request.form["consignee"].upper()
        materialpickupdate=request.form["materialpickupdate"].upper()
        actualpickupdate=request.form["actualpickupdate"].upper()
        etdarbl=request.form["etdarbl"].upper()
        actualetd=request.form["actualetd"].upper()
        etaarbl=request.form["etaarbl"].upper()
        actualeta=request.form["actualeta"].upper()
        countryoforigin=request.form["countryoforigin"].upper()
        portofloading=request.form["portofloading"].upper()
        containersize=request.form["containersize"].upper()
        noofcontainers=request.form["noofcontainers"].upper()
        containernumbers=request.form["containernumbers"].upper()
        mblnumber=request.form["mblnumber"].upper()
        hblnumber=request.form["hblnumber"].upper()
        shippingliner=request.form["shippingliner"].upper()
        firstfeedername=request.form["firstfeedername"].upper()
        firstfeederimono=request.form["firstfeederimono"].upper()
        transhipment1steta=request.form["transhipment1steta"].upper()
        transhipment1stetd=request.form["transhipment1stetd"].upper()
        transhipment1stportname=request.form["transhipment1stportname"].upper()
        mothervesselname=request.form["mothervesselname"].upper()
        secondfeedername=request.form["secondfeedername"].upper()
        transhipment2ndeta=request.form["transhipment2ndeta"].upper()
        transhipment2ndetd=request.form["transhipment2ndetd"].upper()
        transhipment2ndportname=request.form["transhipment2ndportname"].upper()
        prealertdtd=request.form["prealertdtd"].upper()
        remarks=request.form["remarks"].upper()

        sea_form=SEADSR(shipmentmode,ponumber,suppliername,consignee,materialpickupdate,actualpickupdate,etdarbl,actualetd,etaarbl,actualeta,countryoforigin,portofloading,containersize,noofcontainers,containernumbers,mblnumber,hblnumber,shippingliner,firstfeedername,firstfeederimono,transhipment1steta,transhipment1stetd,transhipment1stportname,mothervesselname,secondfeedername,transhipment2ndeta,transhipment2ndetd,transhipment2ndportname,prealertdtd,remarks)
        db.session.add(sea_form)
        db.session.commit()

        flash("Form Submitted Successfully!")
        return redirect(url_for('sea'))

    return render_template('sea_page.html')


@main_bp.route('/dsrseainfo')
def dsrseainfo():
    seainfo=SEADSR.query.all()
    sea_column_names = SEADSR.__table__.columns.keys()
    return render_template('Sea Homepage.html',seainformation=seainfo,sea_column_names = sea_column_names)

@main_bp.route('/seaupdate',methods=['GET','POST'])
def seaupdate():
    if request.method=="POST":
        sea_form=SEADSR.query.get(request.form.get('id'))
        sea_form.shipmentmode=request.form['shipmentmode'].upper()
        sea_form.ponumber=request.form['ponumber'].upper()
        sea_form.suppliername=request.form['suppliername'].upper()
        sea_form.consignee=request.form['consignee'].upper()
        sea_form.materialpickupdate=request.form['materialpickupdate'].upper()
        sea_form.actualpickupdate=request.form['actualpickupdate'].upper()
        sea_form.etdarbl=request.form['etdarbl'].upper()
        sea_form.actualetd=request.form['actualetd'].upper()
        sea_form.etaarbl=request.form['etaarbl'].upper()
        sea_form.actualeta=request.form['actualeta'].upper()
        sea_form.countryoforigin=request.form['countryoforigin'].upper()
        sea_form.portofloading=request.form['portofloading'].upper()
        sea_form.containersize=request.form['containersize'].upper()
        sea_form.noofcontainers=request.form['noofcontainers'].upper()
        sea_form.containernumbers=request.form['containernumbers'].upper()
        sea_form.mblnumber=request.form['mblnumber'].upper()
        sea_form.hblnumber=request.form['hblnumber'].upper()
        sea_form.shippingliner=request.form['shippingliner'].upper()
        sea_form.firstfeedername=request.form['firstfeedername'].upper()
        sea_form.firstfeederimono=request.form['firstfeederimono'].upper()
        sea_form.transhipment1steta=request.form['transhipment1steta'].upper()
        sea_form.transhipment1stetd=request.form['transhipment1stetd'].upper()
        sea_form.transhipment1stportname=request.form['transhipment1stportname'].upper()
        sea_form.mothervesselname=request.form['mothervesselname'].upper()
        sea_form.secondfeedername=request.form['secondfeedername'].upper()
        sea_form.transhipment2ndeta=request.form['transhipment2ndeta'].upper()
        sea_form.transhipment2ndetd=request.form['transhipment2ndetd'].upper()
        sea_form.transhipment2ndportname=request.form['transhipment2ndportname'].upper()
        sea_form.prealertdtd=request.form['prealertdtd'].upper()
        sea_form.remarks=request.form['remarks'].upper()
        db.session.commit()
        flash(f"{sea_form.ponumber} Has Updated Successfully")
        return redirect(url_for('dsrseainfo'))


@main_bp.route('/seadelete/<id>',methods=['GET','POST'])
def seadelete(id):
    sea_form=SEADSR.query.get(id)
    db.session.delete(sea_form)
    db.session.commit()
    flash(f"{sea_form.ponumber} Deleted Successfully")

    remaining_records=SEADSR.query.filter(SEADSR.id > id).all()
    for record in remaining_records:
        record.id -= 1

    db.session.commit()

    return redirect(url_for('dsrseainfo'))



@main_bp.route('/seadownload')
def seadownload():
    # Query data from the database
    data = SEADSR.query.all()

    # Create a CSV file
    csv_filename = 'seadata.csv'
    with open(csv_filename, 'w', newline='') as csvfile:
        csv_writer = csv.writer(csvfile)
        # Write header
        csv_writer.writerow([column.name.upper() for column in SEADSR.__table__.columns])
        # Write data
        for row in data:
            csv_writer.writerow([getattr(row, column.name) for column in SEADSR.__table__.columns])

    # Return the file as a response
    return send_file(csv_filename, as_attachment=True)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choosing Shipment Type</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static',filename='images/Favicon.png') }}" type="image/x-icon">
</head>
<body>
    <div class="container-fluid h-100">
        <header class="d-flex justify-content-between align-items-center p-3">
            <img src="{{ url_for('static',filename='images/Logo.png') }}" alt="Company Logo" class="img-fluid" style="width:280px;">
        </header>
        <main class="d-flex flex-column align-items-center justify-content-center h-100">
            <h1 class="mb-5">TYPES OF SHIPMENT</h1>
            <div class="btn-group-vertical">
                <a href="{{ url_for('air') }}" class="btn btn-primary mb-3 btn-lg" role="button">Air Transport</a>
                <a href="{{ url_for('sea') }}" class="btn btn-primary btn-lg" role="button">Sea Transport</a>
                <!-- <a href="#" class="btn btn-danger btn-lg mt-3" role="button">Info</a> -->
            </div>
        </main>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta http-equiv="Content-Security-Policy" content="default-src 'self';"> -->
    <!-- <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com; style-src 'self' https://maxcdn.bootstrapcdn.com;"> -->
    <!-- Update this line in the head section -->
    <!-- <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' https://maxcdn.bootstrapcdn.com;"> -->

    <title>Login Page</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Add this line in the head section -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="icon" href="{{ url_for('static',filename='images/Favicon.png')}}" type="image/x-icon">
    <!-- <link href="{{ url_for('static',filename='css/login.css') }}" rel="stylesheet"> -->
    <style>
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
        }

        html, body {
            margin: 0;
            padding: 0;
            overflow-y: hidden; /* Hide vertical scrollbar */
        }
        body {
            background-image: url("{{ url_for('static',filename='images/Transport4.jpg')}}");
            /* background-size: cover; */
            /* background-size: 1500px; */
            background-repeat: no-repeat;
            background-position:center; 
        }

        *, *::before, *::after {
            box-sizing: border-box;
        }



        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            /* background-image: url('transport4.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center; */
            border-radius: 50px;
        }


        nav {
            width: 100%;
            padding: 10px 10px;
            display: flex;
            justify-content: right;
            height: 120px;
        }

        .logo {
            width: 110px;
            height: 110px;
            border-radius: 10px;
            cursor: pointer;
            background-color: transparent;
            /* backdrop-filter: blur(15px); */
            /* border: 1px solid red; */
            /* box-shadow: 0 2px 10px rgba(0, 0, 0, 0.20); */
            padding: 5px;
        }

        .content {
            background-color: transparent;
            border-radius: 15px;
            border: 1px solid #fff;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 350px;
            margin-top: -120px;
            padding: 0px 20px;
            backdrop-filter: blur(10px);
            animation: slideBackground 3s linear infinite;
        }

        h1 {
            text-align: center;
            color: #fff;
            font-size: 20px;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            width: 300px;
            background-color: rgb(0, 9, 136);
            border-radius: 5px;
            height: 40px;
            padding: 8px 0px;
            margin-top: 20px;
        }

        .form-group {
            margin-top: 20px;
        }

        label {
            display: block;
            font-weight: bold;
            font-size: 20px;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            margin-top: 20px;
        }

        input {
            width: 300px;
            height: 40px;
            padding: 0px 10px;
            border: 1px solid black;
            border-radius: 5px;
            outline: none;
            margin-top: 10px;
        }

        button {
            width: 300px;
            height: 40px;
            background-color: rgb(0, 9, 136);
            border-radius: 5px;
            color: #fff;
            outline: none;
            border: none;
            font-size: 20px;
            font-family: 'Courier New', Courier, monospace;
            font-weight: bold;
            margin-top: 5px;
        }

        button:hover {
            background-color: rgb(233, 0, 0);
        }

    </style>
</head>
<body>
    <header>
        <nav>
            <img src="{{ url_for('static',filename='images/Favicon.png')}}" class="logo" alt="Img Not Available">   
        </nav>
    </header>
    <main>
        <div class="container">
            <div class="content">
                <h1>LOGIN PAGE</h1>
                <form id="loginForm" action="{{ url_for('main_bp.options') }}">
                    <div class="form-group">
                        <label for="emailInput">E-mail:</label>
                        <input type="email" class="form-control" id="emailInput" name="emailInput" placeholder="E-mail" required>
                    </div>
                    <div class="form-group">
                        <label for="passwordInput">Password:</label>
                        <input type="password" class="form-control" id="passwordInput" name="passwordInput" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" id="loginBtn">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bcryptjs/2.4.3/bcrypt.min.js" defer></script> -->
    <!-- <script src="script.js"></script> -->
</body>
</html>